# 自动获取最新的一言并保存为文件
name: Auto Api Secret

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: "0 0 0,6,12,18 * * ? *"
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests #安装requests
      run: |
        pip install -r requirements.txt
    - name: Read config from secrets  #读取机密
      run: python3 ./main.py    
      - name: Test Api #Api调用
    - name: Commit #上传新的refresh_token到仓库
      run: |
        git config --global user.email bili33@87ouo.top
        git config --global user.name GamerNoTitle
        git add .
        git commit -m "update Hitokoto database" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}